<?php echo $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        
        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
                        ->prependStylesheet($this->basePath('css/style.css'))
        ?>
        
        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('js/main.js'))
            ->prependFile($this->basePath('js/jquery-2.2.4.min.js'))
        ?>
        
    </head>
    <body>
        <div class="container">
            <?php echo $this->content; ?>
        </div>       
        
    </body>
</html>
